run:
	unzip Database_example.zip
	mkdir output
	mkdir output/figures
	python utils/DB_cleaning.py

help:
	@echo -e '################# HELP ##################'
	@echo ''
	@echo -e '    run : runs the database code.'

